/**
 * churn/demoData.js
 * Isolated synthetic customer profiles for Phase 13 Demo / Simulation Mode.
 * These profiles contain realistic combinations of the 21 raw behavioral features
 * designed to naturally exercise all four risk tiers (Low, Medium, High, Very High)
 * through the production XGBoost model artifact (2b2147fd4057).
 *
 * NOTE: These customers are completely isolated and NEVER written to the production
 * MongoDB users, orders, or activities collections.
 */

export const DEMO_CUSTOMERS = [
  // ─── 1. LOW RISK (P < 0.25) ──────────────────────────────────────────
  {
    user_id: "DEMO-LOW-001",
    name: "Sarah Jenkins (Loyal VIP Buyer)",
    email: "sarah.jenkins.demo@lumawear.local",
    isSynthetic: true,
    tenure_days: 420,
    days_since_last_login: 1,
    days_since_last_activity: 1,
    login_count_30d: 18,
    active_days_30d: 14,
    page_views_30d: 52,
    product_views_30d: 34,
    cart_actions_30d: 8,
    wishlist_actions_30d: 5,
    order_count: 9,
    orders_30d: 2,
    days_since_last_order: 4,
    total_spend: 2150.0,
    spend_30d: 420.0,
    average_order_value: 238.89,
    order_frequency: 0.64,
    distinct_products_viewed_30d: 16,
    distinct_categories_ordered: 4,
    items_per_order: 2.8,
    activity_event_count_30d: 78,
    preferred_order_category: "Dresses",
  },
  {
    user_id: "DEMO-LOW-002",
    name: "Marcus Vance (Active Regular)",
    email: "marcus.vance.demo@lumawear.local",
    isSynthetic: true,
    tenure_days: 210,
    days_since_last_login: 2,
    days_since_last_activity: 2,
    login_count_30d: 12,
    active_days_30d: 9,
    page_views_30d: 38,
    product_views_30d: 22,
    cart_actions_30d: 5,
    wishlist_actions_30d: 3,
    order_count: 5,
    orders_30d: 1,
    days_since_last_order: 8,
    total_spend: 980.0,
    spend_30d: 195.0,
    average_order_value: 196.0,
    order_frequency: 0.71,
    distinct_products_viewed_30d: 11,
    distinct_categories_ordered: 3,
    items_per_order: 2.2,
    activity_event_count_30d: 48,
    preferred_order_category: "Shirts",
  },
  {
    user_id: "DEMO-LOW-003",
    name: "Chloe Bennet (Frequent Shopper)",
    email: "chloe.bennet.demo@lumawear.local",
    isSynthetic: true,
    tenure_days: 310,
    days_since_last_login: 3,
    days_since_last_activity: 2,
    login_count_30d: 14,
    active_days_30d: 10,
    page_views_30d: 44,
    product_views_30d: 28,
    cart_actions_30d: 6,
    wishlist_actions_30d: 4,
    order_count: 7,
    orders_30d: 2,
    days_since_last_order: 6,
    total_spend: 1420.0,
    spend_30d: 340.0,
    average_order_value: 202.86,
    order_frequency: 0.68,
    distinct_products_viewed_30d: 14,
    distinct_categories_ordered: 3,
    items_per_order: 2.4,
    activity_event_count_30d: 58,
    preferred_order_category: "Trousers",
  },

  // ─── 2. MEDIUM RISK (0.25 <= P < 0.50) ───────────────────────────────
  {
    user_id: "DEMO-MED-001",
    name: "Elena Rostova (Occasional Buyer)",
    email: "elena.rostova.demo@lumawear.local",
    isSynthetic: true,
    tenure_days: 150,
    days_since_last_login: 12,
    days_since_last_activity: 12,
    login_count_30d: 4,
    active_days_30d: 3,
    page_views_30d: 14,
    product_views_30d: 8,
    cart_actions_30d: 2,
    wishlist_actions_30d: 1,
    order_count: 2,
    orders_30d: 0,
    days_since_last_order: 38,
    total_spend: 340.0,
    spend_30d: 0.0,
    average_order_value: 170.0,
    order_frequency: 0.40,
    distinct_products_viewed_30d: 5,
    distinct_categories_ordered: 2,
    items_per_order: 1.5,
    activity_event_count_30d: 18,
    preferred_order_category: "Shoes",
  },
  {
    user_id: "DEMO-MED-002",
    name: "David Kim (Casual Browser)",
    email: "david.kim.demo@lumawear.local",
    isSynthetic: true,
    tenure_days: 95,
    days_since_last_login: 9,
    days_since_last_activity: 9,
    login_count_30d: 5,
    active_days_30d: 4,
    page_views_30d: 18,
    product_views_30d: 10,
    cart_actions_30d: 1,
    wishlist_actions_30d: 2,
    order_count: 1,
    orders_30d: 0,
    days_since_last_order: 28,
    total_spend: 160.0,
    spend_30d: 0.0,
    average_order_value: 160.0,
    order_frequency: 0.32,
    distinct_products_viewed_30d: 6,
    distinct_categories_ordered: 1,
    items_per_order: 1.0,
    activity_event_count_30d: 22,
    preferred_order_category: "T-Shirts",
  },
  {
    user_id: "DEMO-MED-003",
    name: "Priya Sharma (New Account Explorer)",
    email: "priya.sharma.demo@lumawear.local",
    isSynthetic: true,
    tenure_days: 60,
    days_since_last_login: 7,
    days_since_last_activity: 6,
    login_count_30d: 6,
    active_days_30d: 5,
    page_views_30d: 20,
    product_views_30d: 12,
    cart_actions_30d: 2,
    wishlist_actions_30d: 1,
    order_count: 1,
    orders_30d: 0,
    days_since_last_order: 22,
    total_spend: 190.0,
    spend_30d: 0.0,
    average_order_value: 190.0,
    order_frequency: 0.50,
    distinct_products_viewed_30d: 7,
    distinct_categories_ordered: 1,
    items_per_order: 1.0,
    activity_event_count_30d: 26,
    preferred_order_category: "Accessories",
  },

  // ─── 3. HIGH RISK (0.50 <= P < 0.75) ─────────────────────────────────
  {
    user_id: "DEMO-HIGH-001",
    name: "Jessica Albright (At-Risk Lapsed)",
    email: "jessica.albright.demo@lumawear.local",
    isSynthetic: true,
    tenure_days: 180,
    days_since_last_login: 11,
    days_since_last_activity: 9,
    login_count_30d: 1,
    active_days_30d: 1,
    page_views_30d: 6,
    product_views_30d: 3,
    cart_actions_30d: 1,
    wishlist_actions_30d: 0,
    order_count: 2,
    orders_30d: 0,
    days_since_last_order: 30,
    total_spend: 360.0,
    spend_30d: 0.0,
    average_order_value: 180.0,
    order_frequency: 0.33,
    distinct_products_viewed_30d: 2,
    distinct_categories_ordered: 1,
    items_per_order: 1.8,
    activity_event_count_30d: 6,
    preferred_order_category: "Outerwear",
  },
  {
    user_id: "DEMO-HIGH-002",
    name: "Rachel Sterling (Declining Spender)",
    email: "rachel.sterling.demo@lumawear.local",
    isSynthetic: true,
    tenure_days: 200,
    days_since_last_login: 11,
    days_since_last_activity: 10,
    login_count_30d: 2,
    active_days_30d: 2,
    page_views_30d: 8,
    product_views_30d: 4,
    cart_actions_30d: 1,
    wishlist_actions_30d: 1,
    order_count: 3,
    orders_30d: 0,
    days_since_last_order: 40,
    total_spend: 540.0,
    spend_30d: 0.0,
    average_order_value: 180.0,
    order_frequency: 0.45,
    distinct_products_viewed_30d: 3,
    distinct_categories_ordered: 2,
    items_per_order: 1.8,
    activity_event_count_30d: 8,
    preferred_order_category: "Sweaters",
  },
  {
    user_id: "DEMO-HIGH-003",
    name: "Nathan Drake (Cart Abandoner)",
    email: "nathan.drake.demo@lumawear.local",
    isSynthetic: true,
    tenure_days: 170,
    days_since_last_login: 12,
    days_since_last_activity: 10,
    login_count_30d: 3,
    active_days_30d: 3,
    page_views_30d: 12,
    product_views_30d: 6,
    cart_actions_30d: 2,
    wishlist_actions_30d: 1,
    order_count: 2,
    orders_30d: 0,
    days_since_last_order: 30,
    total_spend: 380.0,
    spend_30d: 0.0,
    average_order_value: 190.0,
    order_frequency: 0.35,
    distinct_products_viewed_30d: 4,
    distinct_categories_ordered: 1,
    items_per_order: 1.5,
    activity_event_count_30d: 12,
    preferred_order_category: "Jackets",
  },

  // ─── 4. VERY HIGH RISK (P >= 0.75) ───────────────────────────────────
  {
    user_id: "DEMO-VHIGH-001",
    name: "Arthur Pendelton (Dormant High-Value VIP)",
    email: "arthur.pendelton.demo@lumawear.local",
    isSynthetic: true,
    tenure_days: 350,
    days_since_last_login: 85,
    days_since_last_activity: 85,
    login_count_30d: 0,
    active_days_30d: 0,
    page_views_30d: 0,
    product_views_30d: 0,
    cart_actions_30d: 0,
    wishlist_actions_30d: 0,
    order_count: 6,
    orders_30d: 0,
    days_since_last_order: 120,
    total_spend: 1450.0,
    spend_30d: 0.0,
    average_order_value: 241.67,
    order_frequency: 0.51,
    distinct_products_viewed_30d: 0,
    distinct_categories_ordered: 3,
    items_per_order: 2.0,
    activity_event_count_30d: 0,
    preferred_order_category: "Jackets",
  },
  {
    user_id: "DEMO-VHIGH-002",
    name: "Victoria Chase (Critical Inactive Churn)",
    email: "victoria.chase.demo@lumawear.local",
    isSynthetic: true,
    tenure_days: 260,
    days_since_last_login: 68,
    days_since_last_activity: 68,
    login_count_30d: 0,
    active_days_30d: 0,
    page_views_30d: 0,
    product_views_30d: 0,
    cart_actions_30d: 0,
    wishlist_actions_30d: 0,
    order_count: 2,
    orders_30d: 0,
    days_since_last_order: 98,
    total_spend: 410.0,
    spend_30d: 0.0,
    average_order_value: 205.0,
    order_frequency: 0.23,
    distinct_products_viewed_30d: 0,
    distinct_categories_ordered: 1,
    items_per_order: 1.5,
    activity_event_count_30d: 0,
    preferred_order_category: "Accessories",
  },
  {
    user_id: "DEMO-VHIGH-003",
    name: "Dominic Toretto (Long-Term Lost Account)",
    email: "dominic.toretto.demo@lumawear.local",
    isSynthetic: true,
    tenure_days: 400,
    days_since_last_login: 95,
    days_since_last_activity: 95,
    login_count_30d: 0,
    active_days_30d: 0,
    page_views_30d: 0,
    product_views_30d: 0,
    cart_actions_30d: 0,
    wishlist_actions_30d: 0,
    order_count: 4,
    orders_30d: 0,
    days_since_last_order: 140,
    total_spend: 880.0,
    spend_30d: 0.0,
    average_order_value: 220.0,
    order_frequency: 0.30,
    distinct_products_viewed_30d: 0,
    distinct_categories_ordered: 2,
    items_per_order: 1.8,
    activity_event_count_30d: 0,
    preferred_order_category: "Shirts",
  },
];

export function isDemoId(userId) {
  return Boolean(userId && String(userId).startsWith("DEMO-"));
}

export function getDemoCustomer(userId) {
  if (!userId) return null;
  const uid = String(userId).trim();
  return DEMO_CUSTOMERS.find((c) => c.user_id === uid) || null;
}
